version: '2'

services:
  react-app:
    build: ../../react-app
    command: "yarn build && cp /build/* /react-app/"
    volumes:
      - ../../react-app:/react-app
      - frontend-dependencies:/react-app/node_modules
  proxy:
    image: nginx:1.13.9-alpine
    restart: always
    volumes:
      - ./nginx-confd:/etc/nginx/conf.d:z
      - ../../react-app/build:/usr/share/nginx/html
    depends_on:
      - react-app
    links:
      - mongodb
      - react-app
    ports:
      - "3001:80"

  mongodb:
      image: mongo:3.6.3-jessie
      environment:
        - MONGO_INITDB_DATABASE=prod
        - MONGO_INITDB_ROOT_USERNAME=prod
        - MONGO_INITDB_ROOT_PASSWORD=prod
      volumes:
        - ./mongo-initdb:/docker-entrypoint-initdb.d:z
      ports:
        - "27017:27017"

  express-app:
    build: ../../express-app
    command: yarn run nodemon
    environment:
      - MONGO_DB_DATABASE=prod
      - MONGO_DB_USERNAME=prod
      - MONGO_DB_PASSWORD=prod
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ../../express-app:/express-app
      - backend-dependencies:/express-app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    restart: always

#node_modules volumes to avoid architecture issues
volumes:
  backend-dependencies:
  frontend-dependencies:
